# Generated by Django 6.0 on 2026-01-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ndiliso_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='village',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ndiliso_api.village'),
        ),
    ]
